# Uncomment the next line to define a global platform for your project
 source 'https://github.com/CocoaPods/Specs.git'
 source 'http://repo.baichuan-ios.taobao.com/baichuanSDK/AliBCSpecs.git'
 source 'https://gitee.com/gokd/kd-IOS-Fleet-In-Specs.git'
# platform :ios, '9.0'

target 'XingLeTao' do
  # Comment the next line if you don't want to use dynamic frameworks
  # use_frameworks!

  # Pods for XingLeTao

  pod 'AFNetworking', '~> 3.2.1'
  pod 'SDWebImage'
  pod 'SDWebImageWebPCoder'
  pod 'MJRefresh'
  pod 'MBProgressHUD'
  pod 'IQKeyboardManager'
  pod 'Masonry'
  pod 'YYText'
  pod 'FCUUID'
  pod 'SJBaseVideoPlayer', :git => 'https://gitee.com/changsanjiang/SJBaseVideoPlayer.git'
  pod 'SJVideoPlayer', :git => 'https://gitee.com/changsanjiang/SJVideoPlayer.git'
  pod 'KTVHTTPCache', '~> 2.0.0'
  
# 淘宝
  pod 'AlibcTradeSDK','4.0.0.8'
  pod 'AliAuthSDK','2.0.0.3'
  pod 'mtopSDK','3.0.0.4'
  pod 'securityGuard','5.4.173'
  pod 'AliLinkPartnerSDK','4.0.0.24'
  pod 'BCUserTrack','5.2.0.11-appkeys'
  pod 'UTDID','1.1.0.16'

  pod 'WindVane','8.5.0.46-bc7-mini'

# umeng
  pod 'UMCCommon'
  pod 'UMCAnalytics'
  pod 'UMCPush'
# 极光
  pod 'JMLink'
# 快电
  pod 'DadaChargeSDK'
# 支付宝
  pod  'AlipaySDK_No_UTDID'
  post_install do |installer|
      installer.pods_project.targets.each do |target|
          target.build_configurations.each do |config|
              if config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'].to_f < 8.0
                  config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '8.0'
              end
          end
      end
  end
end
